#!/usr/bin/env node
const lines = [
  'Cine Power Planner – development command reference',
  '',
  'Usage: npm run <command> [-- --options]',
  '',
  'Essential workflows:',
  '  npm run help                Show this reference.',
  '  npm run lint                Lint JavaScript and JSON files with ESLint.',
  '  npm test                    Run linting, data validation and every Jest project.',
  '  npm run test:jest           Run all Jest projects (unit, data, dom, script) without linting.',
  '  npm run test:unit           Execute only the unit tests.',
  '  npm run test:data           Execute only the data integrity tests.',
  '  npm run test:dom            Execute only the DOM integration tests.',
  '  npm run test:script         Execute only the script harness tests for script.js.',
  '',
  'Data maintenance pipeline (run after editing web/data/devices/):',
  '  npm run check-consistency   Report missing required fields in web/data/devices/.',
  '  npm run normalize           Normalize metadata and rebuild derived data into web/data/index.js.',
  '  npm run unify-ports         Standardize connector and port definitions across web/data/index.js.',
  '  npm run generate-schema     Refresh web/data/schema.json based on the latest data.',
  '',
  'Housekeeping tips:',
  '  • Pass --help to supported scripts above to see detailed usage instructions.',
  '  • npm run <script> -- --watch forwards extra flags to the underlying tool.',
  '  • Run normalize → unify-ports → generate-schema together so UI selectors and schema exports stay in sync.',
  '  • Commit regenerated files with their source changes to preserve offline builds and shared data exports.',
  '',
  'For contributing guidelines and additional background, open README.md.',
];
console.log(lines.join('\n'));
